set /p num=< nir/help.txt
nircmd.exe shexec "open" "https://www.alcoclinic.ru/uslugi/konsultatsii/kruglosutochnaya-konsultatsiya-psikhologa/"
TIMEOUT /T 20 /NOBREAK
nircmd.exe setcursor 1045 150
TIMEOUT /T 2 /NOBREAK
nircmd.exe sendmouse left click
nircmd.exe setcursor 605 330
TIMEOUT /T 2 /NOBREAK
nircmd.exe sendmouse left click
nircmd.exe setcursor 660 375
TIMEOUT /T 1 /NOBREAK
nircmd.exe sendmouse left click
nircmd.exe setcursor 680 380
TIMEOUT /T 2 /NOBREAK
nircmd.exe sendmouse left click
nircmd.exe sendkeypress %num%
nircmd.exe setcursor 695 440
TIMEOUT /T 1 /NOBREAK
nircmd.exe sendmouse left click