set /p num=< nir/help.txt
nircmd.exe shexec "open" "https://luidor-msk.ru/gaz/gazel-biznes"
TIMEOUT /T 10 /NOBREAK
nircmd.exe setcursor 1100 700
TIMEOUT /T 2 /NOBREAK
nircmd.exe sendmouse left click
nircmd.exe sendkeypress 7 %num%
TIMEOUT /T 1 /NOBREAK
nircmd.exe setcursor 1200 700
TIMEOUT /T 1 /NOBREAK
nircmd.exe sendmouse left click